// @ts-check
/**
 * Dev docs sidebar — fully AUTOGENERATED from website/docs (a pristine copy of
 * llm-d/docs). Labels, ordering, and the dev-only "How-to Guides" section are
 * applied by the docs plugin's `sidebarItemsGenerator` (see scripts/lib/sidebar.mjs),
 * so the docs folder needs no _category_.json or frontmatter. Adding a doc is
 * zero-config: it appears on the next build.
 *
 * Released versions use their own frozen versioned_sidebars/*.json instead.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
